// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kfjaqtianmmzwlrzlvto.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtmamFxdGlhbm1tendscnpsdnRvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM4NTY4ODUsImV4cCI6MjA2OTQzMjg4NX0.P6NP-QPRXRxh1cHF3IVigPZENAR9EwLQV4QTuXYK4Nw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});